### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by ZhuYanzhen1** [john-luan/SDR-dongle#1]
请问此仓库中的电路有测试过吗，是否可以使用呢

**Comment by john-luan** [comment]
> 请问此仓库中的电路有测试过吗，是否可以使用呢

R2是DDR RST的上拉，和SD座子冲突。但是实测DDR可以起。
C38要NC，不然可能RST后时序不对PS不启动。
MAX38904C买不到，TPS2121买不到
巴伦封装太小了，只能用LC巴伦，做不到高调谐带宽。

Linux能起，USB能读到，AD9361能读到。
9361 的移植没有做，要用的话需要检查CMOS连线和想办法做射频的测试。我自己review应该没啥问题
